---
# hint for different ctype
hint:
  # for ctype=0
  - en: Which one would you prefer?
    zh: 您愿意哪一个选择?
  # for ctype=1
  - en: 'Please fill in the number that makes the following two options equally attractive:'
    zh: '请填入一个数字, 使您觉得下面的两个选项一样:'
    
# input only for ctype=1
your_ans:
  en: 'Your Answer:'
  zh: '您的回答:'
  
nav:
  next:
    en: 'Next >>'
    zh: '继续 >>'
  submit:
    en: Submit
    zh: 提交

# sets configures question ID array for different sets,
# DO have one or more WHITE SPACE after ',' between each number
# the ID number must be defined in all-ids
sets:
  A: [2, 4, 6, 7, 10, 12, 14, 15, 18, 19, 21, 24]
  B: [1, 3, 5, 8, 9, 11, 13, 16, 17, 20, 22, 23]  
  C: [5, 6, 7, 8]
  
# all-ids contains the ID part of *.yaml file names in 'question' foler
all-ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
